CC=g++
FLAGS=-std=c++20 -Wall -pedantic -Werror -Wextra -Wno-unused-parameter
TEST_LIB=-lgtest -lgtest_main -lpthread

all: wrapper test_bin

wrapper: lab1.o wrapper.cpp
	$(CC) $(FLAGS) lab1.o wrapper.cpp -o wrapper

test_bin: lab1.o lab1_test.cpp
	$(CC) $(FLAGS) lab1.o lab1_test.cpp -o test_bin $(TEST_LIB)


test:
	./test_bin

wrap:
	./wrapper

